services:

  # Konfiguration für die MongoDB mit Replikation.
  mongo1:
    image: mongo:7.0
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017/27018/27019"]

  mongo2:
    image: mongo:7.0
    ports:
      - "27018:27018"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017/27018/27019"]

  mongo3:
    image: mongo:7.0
    ports:
      - "27019:27018"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017/27018/27019"]